unit BankService_Impl;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ This is where you are supposed to code the implementation of your objects. }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}

interface

uses
  {vcl:} Classes, SysUtils, 
  {RemObjects:} uROXMLIntf, uROClientIntf, uROTypes, uROServer, uROServerIntf, uROSessions,
  {Generated:} BankSvrLib_Intf;

type
  { TBankService }
  TBankService = class(TRORemotable, IBankService)
  private
  protected
    { IBankService methods }
    function GetSvrDt: DateTime;
    function QueryAccValue_S(const fSeqno: AnsiString; const AccNo0: AnsiString; var rtMsg: AnsiString; var rtStr: AnsiString): Boolean;
  end;

implementation

uses
  {Generated:} BankSvrLib_Invk,u_Func;

procedure Create_BankService(out anInstance : IUnknown);
begin
  anInstance := TBankService.Create;
end;

{ BankService }
function TBankService.QueryAccValue_S(const fSeqno, AccNo0: AnsiString;
  var rtMsg, rtStr: AnsiString): Boolean;
begin
  Result:=U_ICBCCtl.QueryAccValue_S(fSeqno, AccNo0,rtMsg, rtStr);
end;

function TBankService.GetSvrDt: DateTime;
begin
  Result:=Now();
end;

var
  fClassFactory: IROClassFactory;
initialization
  fClassFactory := TROClassFactory.Create('BankService', Create_BankService, TBankService_Invoker);
  // RegisterForZeroConf(fClassFactory,'_BankService_rosdk._tcp.');

finalization
  UnRegisterClassFactory(fClassFactory);
  fClassFactory := nil;

end.
